package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AbsProvList implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.citiustech.mrr.CPMM1> cpmm;

	private java.lang.Integer cpmmSize;

	public AbsProvList() {
	}

	public java.util.List<com.citiustech.mrr.CPMM1> getCpmm() {
		return this.cpmm;
	}

	public void setCpmm(java.util.List<com.citiustech.mrr.CPMM1> cpmm) {
		this.cpmm = cpmm;
	}

	public java.lang.Integer getCpmmSize() {
		return this.cpmmSize;
	}

	public void setCpmmSize(java.lang.Integer cpmmSize) {
		this.cpmmSize = cpmmSize;
	}

	public AbsProvList(java.util.List<com.citiustech.mrr.CPMM1> cpmm,
			java.lang.Integer cpmmSize) {
		this.cpmm = cpmm;
		this.cpmmSize = cpmmSize;
	}

}