package com.citiustech.mrr;

import java.util.Date;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.persistence.Table(name="CMM_CHSE_LST_WF")
@javax.persistence.Entity
public class CMM1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CMM_ID_GENERATOR", sequenceName = "CMM_ID_SEQ")
	@javax.persistence.Column(name = "CMM_ID")
	@org.kie.api.definition.type.Label(value = "Cmm Id")
	private java.lang.Long cmmId;

	@javax.persistence.Column(name = "CMM_CHSE_CD")
	@org.kie.api.definition.type.Label("Chase Code")
	private java.lang.String cmmChseCd;

	@javax.persistence.Column(name = "MEM_ID")
	@org.kie.api.definition.type.Label("Member Id")
	private java.lang.Long memId;

	@javax.persistence.Column(name = "CMPG_ID")
	@org.kie.api.definition.type.Label("CPMG Id")
	private java.lang.Long cpmgId;

	@javax.persistence.Column(name = "CMPG_CD")
	@org.kie.api.definition.type.Label("Campaign Code")
	private java.lang.String cmpgCd;

	@javax.persistence.Column(name = "MSR_ID")
	@org.kie.api.definition.type.Label("Measure Id")
	private java.lang.Long measureId;

	@javax.persistence.Column(name = "MSR_VER")
	@org.kie.api.definition.type.Label("Measure Code")
	private java.lang.Long msrVer;

	@javax.persistence.Column(name = "MSR_CD")
	@org.kie.api.definition.type.Label("Member Code")
	private java.lang.String msrCd;

	@javax.persistence.Column(name = "SUBMSR_ID")
	@org.kie.api.definition.type.Label("Submsr Id")
	private java.lang.Long submsrId;

	@javax.persistence.Column(name = "SUBMSR_CD")
	@org.kie.api.definition.type.Label("Sub-Measure Code")
	private java.lang.String submsrCd;

	@javax.persistence.Column(name = "CMM_CHSE_STS_MSTR_ID")
	@org.kie.api.definition.type.Label("Chase Id")
	private java.lang.Long cmmChseStsId;

	@javax.persistence.Column(name = "CMM_CHSE_STS_MSTR_CD")
	@org.kie.api.definition.type.Label("Chase Status")
	private java.lang.String cmmChseSts;

	@javax.persistence.Column(name = "ASSGD_TO_LGN_ID")
	@org.kie.api.definition.type.Label("Assign To Login Id")
	private java.lang.String assgdToLgnId;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	@org.kie.api.definition.type.Label("Raw Chase Id")
	private java.lang.Long rawChseId;

	@javax.persistence.Column(name = "CHSE_DUE_DT")
	@org.kie.api.definition.type.Label("Chase Due Date")
	private java.util.Date chseDueDt;

	@javax.persistence.Column(name = "VLD_FRM_DT")
	@org.kie.api.definition.type.Label("Valid From Date")
	private java.util.Date validFromDate;

	@javax.persistence.Column(name = "VLD_TO_DT")
	@org.kie.api.definition.type.Label("Valid To Date")
	private java.util.Date validToDate;

	@javax.persistence.Column(name = "DEL_FLG")
	@org.kie.api.definition.type.Label("Delete Flag")
	private java.lang.Boolean deleted;

	@javax.persistence.Column(name = "RPT_FRM_DT")
	@org.kie.api.definition.type.Label("Report From Date")
	private java.util.Date rptFrom;

	@javax.persistence.Column(name = "RPT_TO_DT")
	@org.kie.api.definition.type.Label("Report To Date")
	private java.util.Date rptTo;

	@javax.persistence.Column(name = "OVRD_CNT")
	@org.kie.api.definition.type.Label("OverRead Count")
	private java.lang.Long ovrdCnt;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Provider List")
	private java.util.List<com.citiustech.mrr.CPMM1> cpmmList;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Counter")
	private java.lang.Integer counter;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Abstractor Counter")
	private java.lang.Integer abstracterCounter;

	@javax.persistence.Column(name = "ACT_CD")
	@org.kie.api.definition.type.Label("Action")
	private java.lang.String action;

	@javax.persistence.Column(name = "ASSGN_TO_USR")
	@org.kie.api.definition.type.Label("Assign To User")
	private java.lang.String assignToUser;

	public CMM1() {
	}

	public java.lang.String getCmmChseCd() {
		return this.cmmChseCd;
	}

	public void setCmmChseCd(java.lang.String cmmChseCd) {
		this.cmmChseCd = cmmChseCd;
	}

	public java.lang.Long getMemId() {
		return this.memId;
	}

	public void setMemId(java.lang.Long memId) {
		this.memId = memId;
	}

	public java.lang.String getCmpgCd() {
		return this.cmpgCd;
	}

	public void setCmpgCd(java.lang.String cmpgCd) {
		this.cmpgCd = cmpgCd;
	}

	public java.lang.Long getMeasureId() {
		return measureId;
	}

	public void setMeasureId(java.lang.Long measureId) {
		this.measureId = measureId;
	}


	public java.lang.Long getMsrVer() {
		return this.msrVer;
	}

	public void setMsrVer(java.lang.Long msrVer) {
		this.msrVer = msrVer;
	}

	public java.lang.String getMsrCd() {
		return this.msrCd;
	}

	public void setMsrCd(java.lang.String msrCd) {
		this.msrCd = msrCd;
	}

	public java.lang.String getSubmsrCd() {
		return this.submsrCd;
	}

	public void setSubmsrCd(java.lang.String submsrCd) {
		this.submsrCd = submsrCd;
	}

	public java.lang.Long getCmmChseStsId() {
		return this.cmmChseStsId;
	}

	public void setCmmChseStsId(java.lang.Long cmmChseStsId) {
		this.cmmChseStsId = cmmChseStsId;
	}

	public java.lang.String getCmmChseSts() {
		return this.cmmChseSts;
	}

	public void setCmmChseSts(java.lang.String cmmChseSts) {
		this.cmmChseSts = cmmChseSts;
	}
	public java.lang.String getAssgdToLgnId() {
		return this.assgdToLgnId;
	}

	public void setAssgdToLgnId(java.lang.String assgdToLgnId) {
		this.assgdToLgnId = assgdToLgnId;
	}

	public java.lang.Long getRawChseId() {
		return this.rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public java.util.Date getChseDueDt() {
		return this.chseDueDt;
	}

	public void setChseDueDt(java.util.Date chseDueDt) {
		this.chseDueDt = chseDueDt;
	}

	public java.util.Date getValidFromDate() {
		return this.validFromDate;
	}

	public void setValidFromDate(java.util.Date validFromDate) {
		this.validFromDate = validFromDate;
	}


	public java.util.Date getValidToDate() {
		return this.validToDate;
	}

	public void setValidToDate(java.util.Date validToDate) {
		this.validToDate = validToDate;
	}

	public java.lang.Boolean getDeleted() {
		return this.deleted;
	}

	public void setDeleted(java.lang.Boolean deleted) {
		this.deleted = deleted;
	}


	public java.lang.Long getCpmgId() {
		return cpmgId;
	}

	public void setCpmgId(java.lang.Long cpmgId) {
		this.cpmgId = cpmgId;
	}

	public java.lang.Long getSubmsrId() {
		return submsrId;
	}

	public void setSubmsrId(java.lang.Long submsrId) {
		this.submsrId = submsrId;
	}

	public java.util.Date getRptFrom() {
		return rptFrom;
	}

	public void setRptFrom(java.util.Date rptFrom) {
		this.rptFrom = rptFrom;
	}

	public java.util.Date getRptTo() {
		return rptTo;
	}

	public void setRptTo(java.util.Date rptTo) {
		this.rptTo = rptTo;
	}

	public java.lang.Long getOvrdCnt() {
		return ovrdCnt;
	}

	public void setOvrdCnt(java.lang.Long ovrdCnt) {
		this.ovrdCnt = ovrdCnt;
	}

	public java.util.List<com.citiustech.mrr.CPMM1> getCpmmList() {
		return this.cpmmList;
	}

	public void setCpmmList(java.util.List<com.citiustech.mrr.CPMM1> cpmmList) {
		this.cpmmList = cpmmList;
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Integer getAbstracterCounter() {
		return this.abstracterCounter;
	}

	public void setAbstracterCounter(java.lang.Integer abstracterCounter) {
		this.abstracterCounter = abstracterCounter;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getAssignToUser() {
		return this.assignToUser;
	}

	public void setAssignToUser(java.lang.String assignToUser) {
		this.assignToUser = assignToUser;
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public CMM1(Long cmmId, String cmmChseCd, Long memId, Long cpmgId, String cmpgCd, Long measureId,
	        Long msrVer, String msrCd, Long submsrId, String submsrCd, Long cmmChseStsId, String cmmChseSts,
	        String assgdToLgnId, Long rawChseId, Date chseDueDt, Date validFromDate, Date validToDate,
	        Boolean deleted, Date rptFrom, Date rptTo, Long ovrdCnt, List<CPMM1> cpmmList, Integer counter,
	        Integer abstracterCounter, String action, String assignToUser) {
		super();
		this.cmmId = cmmId;
		this.cmmChseCd = cmmChseCd;
		this.memId = memId;
		this.cpmgId = cpmgId;
		this.cmpgCd = cmpgCd;
		this.measureId = measureId;
		this.msrVer = msrVer;
		this.msrCd = msrCd;
		this.submsrId = submsrId;
		this.submsrCd = submsrCd;
		this.cmmChseStsId = cmmChseStsId;
		this.cmmChseSts = cmmChseSts;
		this.assgdToLgnId = assgdToLgnId;
		this.rawChseId = rawChseId;
		this.chseDueDt = chseDueDt;
		this.validFromDate = validFromDate;
		this.validToDate = validToDate;
		this.deleted = deleted;
		this.rptFrom = rptFrom;
		this.rptTo = rptTo;
		this.ovrdCnt = ovrdCnt;
		this.cpmmList = cpmmList;
		this.counter = counter;
		this.abstracterCounter = abstracterCounter;
		this.action = action;
		this.assignToUser = assignToUser;
	}


}
