package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CMM1 implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.Column(name = "CMM_CHSE_CD")
	@org.kie.api.definition.type.Label("Chase Code")
	private java.lang.String cmmChseCd;

	@javax.persistence.Column(name = "MEM_ID")
	@org.kie.api.definition.type.Label("Member Id")
	private java.lang.Long memId;

	@javax.persistence.Column(name = "CMPG_CD")
	@org.kie.api.definition.type.Label("Campaign Code")
	private java.lang.String cmpgCd;

	@javax.persistence.Column(name = "MSR_VER")
	@org.kie.api.definition.type.Label("Measure Code")
	private java.lang.String msrVer;

	@javax.persistence.Column(name = "MSR_CD")
	@org.kie.api.definition.type.Label("Member Code")
	private java.lang.String msrCd;

	@javax.persistence.Column(name = "SUBMSR_CD")
	@org.kie.api.definition.type.Label("Sub-Measure Code")
	private java.lang.String submsrCd;

	@javax.persistence.Column(name = "CMM_CHSE_STS")
	@org.kie.api.definition.type.Label("Chase Status")
	private java.lang.String cmmChseSts;

	@javax.persistence.Column(name = "ASSGD_TO_LGN_ID")
	@org.kie.api.definition.type.Label("Assign To Login Id")
	private java.lang.String assgdToLgnId;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	@org.kie.api.definition.type.Label("Raw Chase Id")
	private java.lang.Long rawChseId;

	@javax.persistence.Column(name = "CHSE_DUE_DT")
	@org.kie.api.definition.type.Label("Chase Due Date")
	private java.util.Date chseDueDt;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Provider List")
	private java.util.List<com.citiustech.mrr.CPMM1> cpmmList;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Counter")
	private java.lang.Integer counter;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Abstractor Counter")
	private java.lang.Integer abstracterCounter;

	@javax.persistence.Transient
	@org.kie.api.definition.type.Label("Action")
	private java.lang.String action;

	@javax.persistence.Column(name = "ASSGN_TO_USR")
	@org.kie.api.definition.type.Label("Assign To User")
	private java.lang.String assignToUser;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.IDENTITY/*, generator = "CMM_ID_GENERATOR"*/)
	@javax.persistence.Id
	//@javax.persistence.SequenceGenerator(name = "CMM_ID_GENERATOR", sequenceName = "CMM_ID_SEQ")
	@javax.persistence.Column(name = "CMM_ID")
	@org.kie.api.definition.type.Label(value = "Cmm Id")
	private java.lang.Long cmmId;

	public CMM1() {
	}

	public java.lang.String getCmmChseCd() {
		return this.cmmChseCd;
	}

	public void setCmmChseCd(java.lang.String cmmChseCd) {
		this.cmmChseCd = cmmChseCd;
	}

	public java.lang.Long getMemId() {
		return this.memId;
	}

	public void setMemId(java.lang.Long memId) {
		this.memId = memId;
	}

	public java.lang.String getCmpgCd() {
		return this.cmpgCd;
	}

	public void setCmpgCd(java.lang.String cmpgCd) {
		this.cmpgCd = cmpgCd;
	}

	public java.lang.String getMsrVer() {
		return this.msrVer;
	}

	public void setMsrVer(java.lang.String msrVer) {
		this.msrVer = msrVer;
	}

	public java.lang.String getMsrCd() {
		return this.msrCd;
	}

	public void setMsrCd(java.lang.String msrCd) {
		this.msrCd = msrCd;
	}

	public java.lang.String getSubmsrCd() {
		return this.submsrCd;
	}

	public void setSubmsrCd(java.lang.String submsrCd) {
		this.submsrCd = submsrCd;
	}

	public java.lang.String getCmmChseSts() {
		return this.cmmChseSts;
	}

	public void setCmmChseSts(java.lang.String cmmChseSts) {
		this.cmmChseSts = cmmChseSts;
	}

	public java.lang.String getAssgdToLgnId() {
		return this.assgdToLgnId;
	}

	public void setAssgdToLgnId(java.lang.String assgdToLgnId) {
		this.assgdToLgnId = assgdToLgnId;
	}

	public java.lang.Long getRawChseId() {
		return this.rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public java.util.Date getChseDueDt() {
		return this.chseDueDt;
	}

	public void setChseDueDt(java.util.Date chseDueDt) {
		this.chseDueDt = chseDueDt;
	}

	public java.util.List<com.citiustech.mrr.CPMM1> getCpmmList() {
		return this.cpmmList;
	}

	public void setCpmmList(java.util.List<com.citiustech.mrr.CPMM1> cpmmList) {
		this.cpmmList = cpmmList;
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Integer getAbstracterCounter() {
		return this.abstracterCounter;
	}

	public void setAbstracterCounter(java.lang.Integer abstracterCounter) {
		this.abstracterCounter = abstracterCounter;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getAssignToUser() {
		return this.assignToUser;
	}

	public void setAssignToUser(java.lang.String assignToUser) {
		this.assignToUser = assignToUser;
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public CMM1(java.lang.String cmmChseCd, java.lang.Long memId,
			java.lang.String cmpgCd, java.lang.String msrVer,
			java.lang.String msrCd, java.lang.String submsrCd,
			java.lang.String cmmChseSts, java.lang.String assgdToLgnId,
			java.lang.Long rawChseId, java.util.Date chseDueDt,
			java.util.List<com.citiustech.mrr.CPMM1> cpmmList,
			java.lang.Integer counter, java.lang.Integer abstracterCounter,
			java.lang.String action, java.lang.String assignToUser,
			java.lang.Long cmmId) {
		this.cmmChseCd = cmmChseCd;
		this.memId = memId;
		this.cmpgCd = cmpgCd;
		this.msrVer = msrVer;
		this.msrCd = msrCd;
		this.submsrCd = submsrCd;
		this.cmmChseSts = cmmChseSts;
		this.assgdToLgnId = assgdToLgnId;
		this.rawChseId = rawChseId;
		this.chseDueDt = chseDueDt;
		this.cpmmList = cpmmList;
		this.counter = counter;
		this.abstracterCounter = abstracterCounter;
		this.action = action;
		this.assignToUser = assignToUser;
		this.cmmId = cmmId;
	}

}