package com.citiustech.mrr;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */
@javax.persistence.Table(name="CPMM_CHSE_LST_WF")
@javax.persistence.Entity
public class CPMM1 implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CPMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CPMM_ID_GENERATOR", sequenceName = "CPMM_ID_SEQ")
	@org.kie.api.definition.type.Label("Cpmm Id")
	@javax.persistence.Column(name = "CPMM_ID")
	private java.lang.Long cpmmId;

	@javax.persistence.Column(name = "CPMM_CHSE_CD")
	@org.kie.api.definition.type.Label("Chase Code")
	private java.lang.String cpmmChseCd;

	@javax.persistence.Column(name = "CMM_ID")
	@org.kie.api.definition.type.Label("Cmm Id")
	private java.lang.Long cmmId;

	@javax.persistence.Column(name = "CMM_CHSE_CD")
	@org.kie.api.definition.type.Label("CMM Chase Code")
	private java.lang.String cmmChaseCode;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	@org.kie.api.definition.type.Label("Raw Chase Id")
	private java.lang.Long rawChseId;

	@javax.persistence.Column(name = "CMPG_ID")
	@org.kie.api.definition.type.Label("CPMG Id")
	private java.lang.Long cpmgId;

	@javax.persistence.Column(name = "CMPG_CD")
	@org.kie.api.definition.type.Label("Campaign Code")
	private java.lang.String cmpgCd;

	@javax.persistence.Column(name = "MEM_ID")
	@org.kie.api.definition.type.Label("Member Id")
	private java.lang.Long memId;

	@javax.persistence.Column(name = "ADDR_MSTR_ID")
	@org.kie.api.definition.type.Label("Address Master Id")
	private java.lang.Long addrId;

	@javax.persistence.Column(name = "ADDR_ZIP_CD")
	@org.kie.api.definition.type.Label("Zip Code")
	private java.lang.String addrZipCd;

    @javax.persistence.Column(name = "PROV_ID")
	@org.kie.api.definition.type.Label("Provider Id")
	private java.lang.Long provId;

    @javax.persistence.Column(name = "PROV_TYP_IND")
	@org.kie.api.definition.type.Label("Prov Type Ind")
	private java.lang.String provTypeInd;

	@javax.persistence.Column(name = "MSR_VER")
	@org.kie.api.definition.type.Label("Measure Version")
	private java.lang.Long msrVer;

	@javax.persistence.Column(name = "MSR_ID")
	@org.kie.api.definition.type.Label("Measure Id")
	private java.lang.Long measureId;

	@javax.persistence.Column(name = "MSR_CD")
	@org.kie.api.definition.type.Label("Measure Code")
	private java.lang.String msrCd;

	@javax.persistence.Column(name = "SUBMSR_ID")
	@org.kie.api.definition.type.Label("Submsr Id")
	private java.lang.Long submsrId;

	@javax.persistence.Column(name = "SUBMSR_CD")
	@org.kie.api.definition.type.Label("Sub-Measure Code")
	private java.lang.String submsrCd;

	@javax.persistence.Column(name = "HLTHPLN_ID")
	@org.kie.api.definition.type.Label("Health Plan Id")
	private java.lang.Long healthPlanId;

	@javax.persistence.Column(name = "HLTHPLN_CD")
	@org.kie.api.definition.type.Label("Health Plan Code")
	private java.lang.String healthPlanCd;

	@javax.persistence.Column(name = "LOB_ID")
	@org.kie.api.definition.type.Label("Line Of Business ID")
	private java.lang.Long lobId;

	@javax.persistence.Column(name = "LOB_CD")
	@org.kie.api.definition.type.Label("Line Of Business CD")
	private java.lang.String lobCd;

	@javax.persistence.Column(name = "PROD_ID")
	@org.kie.api.definition.type.Label("Product ID")
	private java.lang.Long prodId;

	@javax.persistence.Column(name = "PROD_CD")
	@org.kie.api.definition.type.Label("Product Code")
	private java.lang.String productCode;

	@javax.persistence.Column(name = "MOC_DTL_ID")
	@org.kie.api.definition.type.Label("Moc Details Id")
	private java.lang.Long mocDtlId;

	@javax.persistence.Column(name = "DNRTR_QLFNG_EVNT_DT")
	@org.kie.api.definition.type.Label("Denominator Qualifying Event Date")
	private java.util.Date denominatorQualifyingEventDate;

	@javax.persistence.Column(name = "ASSGD_TO_LGN_ID")
	@org.kie.api.definition.type.Label("Assign To User")
	private java.lang.String assgdToUser;

	@javax.persistence.Column(name = "CPMM_CHSE_DUE_DT")
	@org.kie.api.definition.type.Label("Chase Due Date")
	private java.util.Date chseDueDt;

	@javax.persistence.Column(name = "CPMM_CHSE_STS_MSTR_ID")
	@org.kie.api.definition.type.Label("CPMM_CHSE_STS_MSTR_ID")
	private java.lang.Long cpmmChaseStatusMasterId;

	@javax.persistence.Column(name = "CPMM_CHSE_STS_MSTR_CD")
	@org.kie.api.definition.type.Label("Chase Status Code")
	private java.lang.String cpmmChseStsCd;

	@javax.persistence.Column(name = "CP_CHSE_CD")
	@org.kie.api.definition.type.Label("CP Chase Code")
	private java.lang.String cpChaseCode;

	@javax.persistence.Column(name = "OVRD_CNT")
	@org.kie.api.definition.type.Label("Override Count")
	private java.lang.Long overrideCount;

	@javax.persistence.Column(name = "WRKFL_INST_ID")
	@org.kie.api.definition.type.Label("WF Instance Id")
	private java.lang.Long workflowInstanceId;

	@javax.persistence.Column(name = "VLD_FRM_DT")
	@org.kie.api.definition.type.Label("Valid From Date")
	private java.util.Date validFromDate;

	@javax.persistence.Column(name = "VLD_TO_DT")
	@org.kie.api.definition.type.Label("Valid TO Date")
	private java.util.Date validToDate;

	@javax.persistence.Column(name = "DEL_FLG")
	@org.kie.api.definition.type.Label("Delete Flag")
	private java.lang.Boolean deleted;

	@javax.persistence.Column(name = "ACT_CD")
	@org.kie.api.definition.type.Label("Action")
	private java.lang.String action;

	@javax.persistence.Column(name = "LOGIN_USR")
	@org.kie.api.definition.type.Label("Login User")
	private java.lang.String loginUser;

	@javax.persistence.Column(name = "PRVS_ACTY")
	@org.kie.api.definition.type.Label("Previous Activity")
	private java.lang.String previousActivity;

	@javax.persistence.Column(name = "SUB_PROCESS_INSTANCE_ID")
	@org.kie.api.definition.type.Label(value = "Sub Process Instance Id")
	private java.lang.Long subProcessInstanceId;
	
	@javax.persistence.Column(name = "OWNER")
	@org.kie.api.definition.type.Label(value = "Owner")
	private java.lang.String owner;

	public CPMM1() {
	}

	public java.lang.Long getCpmmId() {
		return cpmmId;
	}

	public void setCpmmId(java.lang.Long cpmmId) {
		this.cpmmId = cpmmId;
	}

	public java.lang.String getCpmmChseCd() {
		return cpmmChseCd;
	}

	public void setCpmmChseCd(java.lang.String cpmmChseCd) {
		this.cpmmChseCd = cpmmChseCd;
	}

	public java.lang.Long getCmmId() {
		return cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public java.lang.String getCmmChaseCode() {
		return cmmChaseCode;
	}

	public void setCmmChaseCode(java.lang.String cmmChaseCode) {
		this.cmmChaseCode = cmmChaseCode;
	}

	public java.lang.Long getRawChseId() {
		return rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public java.lang.Long getProvId() {
		return provId;
	}

	public void setProvId(java.lang.Long provId) {
		this.provId = provId;
	}

	public java.lang.String getCmpgCd() {
		return cmpgCd;
	}

	public void setCmpgCd(java.lang.String cmpgCd) {
		this.cmpgCd = cmpgCd;
	}

	public java.lang.Long getMemId() {
		return memId;
	}

	public void setMemId(java.lang.Long memId) {
		this.memId = memId;
	}

	public java.lang.Long getAddrId() {
		return addrId;
	}

	public void setAddrId(java.lang.Long addrId) {
		this.addrId = addrId;
	}

	public java.lang.Long getMeasureId() {
		return measureId;
	}

	public void setMeasureId(java.lang.Long measureId) {
		this.measureId = measureId;
	}

	public java.lang.Long getMsrVer() {
		return msrVer;
	}

	public void setMsrVer(java.lang.Long msrVer) {
		this.msrVer = msrVer;
	}

	public java.lang.String getMsrCd() {
		return msrCd;
	}

	public void setMsrCd(java.lang.String msrCd) {
		this.msrCd = msrCd;
	}

	public java.lang.String getSubmsrCd() {
		return submsrCd;
	}

	public void setSubmsrCd(java.lang.String submsrCd) {
		this.submsrCd = submsrCd;
	}

	public java.lang.Long getHealthPlan() {
		return healthPlanId;
	}

	public void setHealthPlan(java.lang.Long healthPlanId) {
		this.healthPlanId = healthPlanId;
	}

	public java.lang.String getProductCode() {
		return productCode;
	}

	public void setProductCode(java.lang.String productCode) {
		this.productCode = productCode;
	}

	public java.lang.Long getMocDtlId() {
		return mocDtlId;
	}

	public void setMocDtlId(java.lang.Long mocDtlId) {
		this.mocDtlId = mocDtlId;
	}

	public java.util.Date getDenominatorQualifyingEventDate() {
		return denominatorQualifyingEventDate;
	}

	public void setDenominatorQualifyingEventDate(java.util.Date denominatorQualifyingEventDate) {
		this.denominatorQualifyingEventDate = denominatorQualifyingEventDate;
	}

	public java.lang.String getAssgdToUser() {
		return assgdToUser;
	}

	public void setAssgdToUser(java.lang.String assgdToUser) {
		this.assgdToUser = assgdToUser;
	}

	public java.util.Date getChseDueDt() {
		return chseDueDt;
	}

	public void setChseDueDt(java.util.Date chseDueDt) {
		this.chseDueDt = chseDueDt;
	}

	public java.lang.Long getCpmmChaseStatusMasterId() {
		return cpmmChaseStatusMasterId;
	}

	public void setCpmmChaseStatusMasterId(java.lang.Long cpmmChaseStatusMasterId) {
		this.cpmmChaseStatusMasterId = cpmmChaseStatusMasterId;
	}

	public java.lang.String getCpmmChseStsCd() {
		return cpmmChseStsCd;
	}

	public void setCpmmChseStsCd(java.lang.String cpmmChseStsCd) {
		this.cpmmChseStsCd = cpmmChseStsCd;
	}

	public java.lang.String getCpChaseCode() {
		return cpChaseCode;
	}

	public void setCpChaseCode(java.lang.String cpChaseCode) {
		this.cpChaseCode = cpChaseCode;
	}

	public java.lang.Long getOverrideCount() {
		return overrideCount;
	}

	public void setOverrideCount(java.lang.Long overrideCount) {
		this.overrideCount = overrideCount;
	}

	public java.lang.Long getWorkflowInstanceId() {
		return workflowInstanceId;
	}

	public void setWorkflowInstanceId(java.lang.Long workflowInstanceId) {
		this.workflowInstanceId = workflowInstanceId;
	}

	public java.util.Date getValidFromDate() {
		return validFromDate;
	}

	public void setValidFromDate(java.util.Date validFromDate) {
		this.validFromDate = validFromDate;
	}

	public java.util.Date getValidToDate() {
		return validToDate;
	}

	public void setValidToDate(java.util.Date validToDate) {
		this.validToDate = validToDate;
	}

	public java.lang.Boolean getDeleted() {
		return deleted;
	}

	public void setDeleted(java.lang.Boolean deleted) {
		this.deleted = deleted;
	}

	public java.lang.String getAddrZipCd() {
		return addrZipCd;
	}

	public void setAddrZipCd(java.lang.String addrZipCd) {
		this.addrZipCd = addrZipCd;
	}

	public java.lang.String getAction() {
		return action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getLoginUser() {
		return loginUser;
	}

	public void setLoginUser(java.lang.String loginUser) {
		this.loginUser = loginUser;
	}

	public java.lang.String getPreviousActivity() {
		return previousActivity;
	}

	public void setPreviousActivity(java.lang.String previousActivity) {
		this.previousActivity = previousActivity;
	}

	public java.lang.Long getSubProcessInstanceId() {
		return subProcessInstanceId;
	}

	public void setSubProcessInstanceId(java.lang.Long subProcessInstanceId) {
		this.subProcessInstanceId = subProcessInstanceId;
	}

	public java.lang.Long getCpmgId() {
		return cpmgId;
	}

	public void setCpmgId(java.lang.Long cpmgId) {
		this.cpmgId = cpmgId;
	}

	public java.lang.String getProvTypeInd() {
		return provTypeInd;
	}

	public void setProvTypeInd(java.lang.String provTypeInd) {
		this.provTypeInd = provTypeInd;
	}

	public java.lang.Long getSubmsrId() {
		return submsrId;
	}

	public void setSubmsrId(java.lang.Long submsrId) {
		this.submsrId = submsrId;
	}

	public java.lang.Long getHealthPlanId() {
		return healthPlanId;
	}

	public void setHealthPlanId(java.lang.Long healthPlanId) {
		this.healthPlanId = healthPlanId;
	}

	public java.lang.String getHealthPlanCd() {
		return healthPlanCd;
	}

	public void setHealthPlanCd(java.lang.String healthPlanCd) {
		this.healthPlanCd = healthPlanCd;
	}

	public java.lang.Long getLobId() {
		return lobId;
	}

	public void setLobId(java.lang.Long lobId) {
		this.lobId = lobId;
	}

	public java.lang.String getLobCd() {
		return lobCd;
	}

	public void setLobCd(java.lang.String lobCd) {
		this.lobCd = lobCd;
	}

	public java.lang.Long getProdId() {
		return prodId;
	}

	public void setProdId(java.lang.Long prodId) {
		this.prodId = prodId;
	}
	
	public java.lang.String getOwner() {
		return owner;
	}

	public void setOwner(java.lang.String owner) {
		this.owner = owner;
	}

	public CPMM1(Long cpmmId, String cpmmChseCd, Long cmmId, String cmmChaseCode, Long rawChseId, Long cpmgId,
	        String cmpgCd, Long memId, Long addrId, String addrZipCd, Long provId, String provTypeInd,
	        Long msrVer, Long measureId, String msrCd, Long submsrId, String submsrCd, Long healthPlanId,
	        String healthPlanCd, Long lobId, String lobCd, Long prodId, String productCode, Long mocDtlId,
	        Date denominatorQualifyingEventDate, String assgdToUser, Date chseDueDt,
	        Long cpmmChaseStatusMasterId, String cpmmChseStsCd, String cpChaseCode, Long overrideCount,
	        Long workflowInstanceId, Date validFromDate, Date validToDate, Boolean deleted, String action,
	        String loginUser, String previousActivity, Long subProcessInstanceId, String owner) {
		super();
		this.cpmmId = cpmmId;
		this.cpmmChseCd = cpmmChseCd;
		this.cmmId = cmmId;
		this.cmmChaseCode = cmmChaseCode;
		this.rawChseId = rawChseId;
		this.cpmgId = cpmgId;
		this.cmpgCd = cmpgCd;
		this.memId = memId;
		this.addrId = addrId;
		this.addrZipCd = addrZipCd;
		this.provId = provId;
		this.provTypeInd = provTypeInd;
		this.msrVer = msrVer;
		this.measureId = measureId;
		this.msrCd = msrCd;
		this.submsrId = submsrId;
		this.submsrCd = submsrCd;
		this.healthPlanId = healthPlanId;
		this.healthPlanCd = healthPlanCd;
		this.lobId = lobId;
		this.lobCd = lobCd;
		this.prodId = prodId;
		this.productCode = productCode;
		this.mocDtlId = mocDtlId;
		this.denominatorQualifyingEventDate = denominatorQualifyingEventDate;
		this.assgdToUser = assgdToUser;
		this.chseDueDt = chseDueDt;
		this.cpmmChaseStatusMasterId = cpmmChaseStatusMasterId;
		this.cpmmChseStsCd = cpmmChseStsCd;
		this.cpChaseCode = cpChaseCode;
		this.overrideCount = overrideCount;
		this.workflowInstanceId = workflowInstanceId;
		this.validFromDate = validFromDate;
		this.validToDate = validToDate;
		this.deleted = deleted;
		this.action = action;
		this.loginUser = loginUser;
		this.previousActivity = previousActivity;
		this.subProcessInstanceId = subProcessInstanceId;
		this.owner = owner;
	}


}
