package com.citiustech.mrr.signaleventpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class listOfProviders implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public listOfProviders() {
    }




}