package com.citiustech.mrr.signaleventpoc;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LoopBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("counter")
	private Integer counter;
	@org.kie.api.definition.type.Label("MaxLoop")
	private Integer maxLoop;

	@org.kie.api.definition.type.Label("abstracterCounter")
	private int abstracterCounter;

	@org.kie.api.definition.type.Label("parentProcessID")
	private String parentProcessID;

	@org.kie.api.definition.type.Label("subProcessID")
	private String subProcessID;

	public LoopBO() {
	}

	public java.lang.Integer getCounter() {
		return this.counter;
	}

	public void setCounter(java.lang.Integer counter) {
		this.counter = counter;
	}

	public java.lang.Integer getMaxLoop() {
		return this.maxLoop;
	}

	public void setMaxLoop(java.lang.Integer maxLoop) {
		this.maxLoop = maxLoop;
	}

	public java.lang.String getParentProcessID() {
		return this.parentProcessID;
	}

	public void setParentProcessID(java.lang.String parentProcessID) {
		this.parentProcessID = parentProcessID;
	}

	public java.lang.String getSubProcessID() {
		return this.subProcessID;
	}

	public void setSubProcessID(java.lang.String subProcessID) {
		this.subProcessID = subProcessID;
	}

	public int getAbstracterCounter() {
		return this.abstracterCounter;
	}

	public void setAbstracterCounter(int abstracterCounter) {
		this.abstracterCounter = abstracterCounter;
	}

	public LoopBO(java.lang.Integer counter, java.lang.Integer maxLoop,
			int abstracterCounter, java.lang.String parentProcessID,
			java.lang.String subProcessID) {
		this.counter = counter;
		this.maxLoop = maxLoop;
		this.abstracterCounter = abstracterCounter;
		this.parentProcessID = parentProcessID;
		this.subProcessID = subProcessID;
	}

}