package com.myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CMM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CMM_ID_GENERATOR", sequenceName = "CMM_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("CMM_ID")
	private java.lang.Long cmmId;

	@org.kie.api.definition.type.Label("MEM_ID")
	private java.lang.Long memId;

	@org.kie.api.definition.type.Label("MSR_ID")
	private java.lang.Long msrId;

	@org.kie.api.definition.type.Label("CHASE_STATUS")
	private java.lang.String chaseStatus;

	//@javax.persistence.OneToMany(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	//@org.kie.api.definition.type.Label(value = "CPMM_LIST")
	@javax.persistence.Transient
	private java.util.List<com.myteam.CPMM> cpmmList;

	public CMM() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public java.lang.Long getMemId() {
		return this.memId;
	}

	public void setMemId(java.lang.Long memId) {
		this.memId = memId;
	}

	public java.lang.Long getMsrId() {
		return this.msrId;
	}

	public void setMsrId(java.lang.Long msrId) {
		this.msrId = msrId;
	}

	public java.lang.String getChaseStatus() {
		return this.chaseStatus;
	}

	public void setChaseStatus(java.lang.String chaseStatus) {
		this.chaseStatus = chaseStatus;
	}

	public java.util.List<com.myteam.CPMM> getCpmmList() {
		return this.cpmmList;
	}

	public void setCpmmList(java.util.List<com.myteam.CPMM> cpmmList) {
		this.cpmmList = cpmmList;
	}

	public CMM(java.lang.Long id, java.lang.Long cmmId, java.lang.Long memId,
			java.lang.Long msrId, java.lang.String chaseStatus,
			java.util.List<com.myteam.CPMM> cpmmList) {
		this.id = id;
		this.cmmId = cmmId;
		this.memId = memId;
		this.msrId = msrId;
		this.chaseStatus = chaseStatus;
		this.cpmmList = cpmmList;
	}

}