package com.myteam;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CPMM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CPMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CPMM_ID_GENERATOR", sequenceName = "CPMM_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "CPMM_ID")
	private java.lang.Long cpmmId;

	@org.kie.api.definition.type.Label(value = "ZIP_CODE")
	private java.lang.Long zipCode;

	@org.kie.api.definition.type.Label(value = "PROVIDER_ID")
	private java.lang.Long providerId;

	@org.kie.api.definition.type.Label(value = "PROVIDER_STATUS")
	private java.lang.String providerStatus;

	@org.kie.api.definition.type.Label(value = "CMPG_CD")
	private java.lang.String cmpgCd;

	@org.kie.api.definition.type.Label(value = "MEMBER_ID")
	private java.lang.Long memberId;

	public CPMM() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getCpmmId() {
		return this.cpmmId;
	}

	public void setCpmmId(java.lang.Long cpmmId) {
		this.cpmmId = cpmmId;
	}

	public java.lang.Long getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(java.lang.Long zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.Long getProviderId() {
		return this.providerId;
	}

	public void setProviderId(java.lang.Long providerId) {
		this.providerId = providerId;
	}

	public java.lang.String getProviderStatus() {
		return this.providerStatus;
	}

	public void setProviderStatus(java.lang.String providerStatus) {
		this.providerStatus = providerStatus;
	}

	public java.lang.String getCmpgCd() {
		return this.cmpgCd;
	}

	public void setCmpgCd(java.lang.String cmpgCd) {
		this.cmpgCd = cmpgCd;
	}

	public java.lang.Long getMemberId() {
		return this.memberId;
	}

	public void setMemberId(java.lang.Long memberId) {
		this.memberId = memberId;
	}

	public CPMM(java.lang.Long id, java.lang.Long cpmmId,
			java.lang.Long zipCode, java.lang.Long providerId,
			java.lang.String providerStatus, java.lang.String cmpgCd,
			java.lang.Long memberId) {
		this.id = id;
		this.cpmmId = cpmmId;
		this.zipCode = zipCode;
		this.providerId = providerId;
		this.providerStatus = providerStatus;
		this.cmpgCd = cmpgCd;
		this.memberId = memberId;
	}

}