package com.citiustech.mrr.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CMM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CMM_ID_GENERATOR", sequenceName = "CMM_ID_SEQ")
	@javax.persistence.Column(name = "CMM_ID")
	private java.lang.Long cmmId;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	private java.lang.Long rawChseId;

	@javax.persistence.Transient
	private java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList;

	public CMM() {
	}

	public java.lang.Long getCmmId() {
		return this.cmmId;
	}

	public void setCmmId(java.lang.Long cmmId) {
		this.cmmId = cmmId;
	}

	public java.lang.Long getRawChseId() {
		return this.rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public java.util.List<com.citiustech.mrr.sample.CPMM> getCpmmList() {
		return this.cpmmList;
	}

	public void setCpmmList(
			java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList) {
		this.cpmmList = cpmmList;
	}

	public CMM(java.lang.Long cmmId, java.lang.Long rawChseId,
			java.util.List<com.citiustech.mrr.sample.CPMM> cpmmList) {
		this.cmmId = cmmId;
		this.rawChseId = rawChseId;
		this.cpmmList = cpmmList;
	}

}