package com.citiustech.mrr.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CPMM implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CPMM_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "CPMM_ID_GENERATOR", sequenceName = "CPMM_ID_SEQ")
	@javax.persistence.Column(name = "CPMM_ID")
	private java.lang.Long cpmmId;

	@javax.persistence.Column(name = "RAW_CHSE_ID")
	private java.lang.Long rawChseId;

	public CPMM() {
	}

	public java.lang.Long getCpmmId() {
		return this.cpmmId;
	}

	public void setCpmmId(java.lang.Long cpmmId) {
		this.cpmmId = cpmmId;
	}

	public java.lang.Long getRawChseId() {
		return this.rawChseId;
	}

	public void setRawChseId(java.lang.Long rawChseId) {
		this.rawChseId = rawChseId;
	}

	public CPMM(java.lang.Long cpmmId, java.lang.Long rawChseId) {
		this.cpmmId = cpmmId;
		this.rawChseId = rawChseId;
	}

}