package com.citiustech.mrr.mrrbpmproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Chase implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("measure")
	private java.lang.String measure;
	@org.kie.api.definition.type.Label("modeOfCommunication")
	private java.lang.String modeOfCommunication;
	@org.kie.api.definition.type.Label("nextRole")
	private java.lang.String nextRole;
	@org.kie.api.definition.type.Label("nextTask")
	private java.lang.String nextTask;
	@org.kie.api.definition.type.Label("nextUser")
	private java.lang.String nextUser;
	@org.kie.api.definition.type.Label("previousTask")
	private java.lang.String previousTask;
	@org.kie.api.definition.type.Label("taskName")
	private java.lang.String taskName;
	@org.kie.api.definition.type.Label("updateModel")
	private java.lang.String updateModel;
	@org.kie.api.definition.type.Label("zipCode")
	private int zipCode;

	@org.kie.api.definition.type.Label(value = "nextTaskName")
	private java.lang.String nextTaskName;

	public Chase() {
	}

	public java.lang.String getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.String measure) {
		this.measure = measure;
	}

	public java.lang.String getModeOfCommunication() {
		return this.modeOfCommunication;
	}

	public void setModeOfCommunication(java.lang.String modeOfCommunication) {
		this.modeOfCommunication = modeOfCommunication;
	}

	public java.lang.String getNextRole() {
		return this.nextRole;
	}

	public void setNextRole(java.lang.String nextRole) {
		this.nextRole = nextRole;
	}

	public java.lang.String getNextTask() {
		return this.nextTask;
	}

	public void setNextTask(java.lang.String nextTask) {
		this.nextTask = nextTask;
	}

	public java.lang.String getNextUser() {
		return this.nextUser;
	}

	public void setNextUser(java.lang.String nextUser) {
		this.nextUser = nextUser;
	}

	public java.lang.String getPreviousTask() {
		return this.previousTask;
	}

	public void setPreviousTask(java.lang.String previousTask) {
		this.previousTask = previousTask;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.String getUpdateModel() {
		return this.updateModel;
	}

	public void setUpdateModel(java.lang.String updateModel) {
		this.updateModel = updateModel;
	}

	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getNextTaskName() {
		return this.nextTaskName;
	}

	public void setNextTaskName(java.lang.String nextTaskName) {
		this.nextTaskName = nextTaskName;
	}

	public Chase(java.lang.String measure,
			java.lang.String modeOfCommunication, java.lang.String nextRole,
			java.lang.String nextTask, java.lang.String nextUser,
			java.lang.String previousTask, java.lang.String taskName,
			java.lang.String updateModel, int zipCode,
			java.lang.String nextTaskName) {
		this.measure = measure;
		this.modeOfCommunication = modeOfCommunication;
		this.nextRole = nextRole;
		this.nextTask = nextTask;
		this.nextUser = nextUser;
		this.previousTask = previousTask;
		this.taskName = taskName;
		this.updateModel = updateModel;
		this.zipCode = zipCode;
		this.nextTaskName = nextTaskName;
	}

}