package com.citiustech.mrr.mrrmultiinstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BRGetUserStatusBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "user")
	private java.lang.String user;
	@org.kie.api.definition.type.Label(value = "measure")
	private java.lang.String measure;
	@org.kie.api.definition.type.Label(value = "zipCode")
	private int zipCode;
	@org.kie.api.definition.type.Label(value = "provider")
	private java.lang.String provider;
	@org.kie.api.definition.type.Label(value = "lastUser")
	private java.lang.String lastUser;
	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;

	public BRGetUserStatusBO() {
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.lang.String getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.String measure) {
		this.measure = measure;
	}

	public int getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(int zipCode) {
		this.zipCode = zipCode;
	}

	public java.lang.String getProvider() {
		return this.provider;
	}

	public void setProvider(java.lang.String provider) {
		this.provider = provider;
	}

	public java.lang.String getLastUser() {
		return this.lastUser;
	}

	public void setLastUser(java.lang.String lastUser) {
		this.lastUser = lastUser;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public BRGetUserStatusBO(java.lang.String user, java.lang.String measure,
			int zipCode, java.lang.String provider, java.lang.String lastUser,
			java.lang.String status) {
		this.user = user;
		this.measure = measure;
		this.zipCode = zipCode;
		this.provider = provider;
		this.lastUser = lastUser;
		this.status = status;
	}

}