package com.citiustech.mrr.mrrmultiinstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ChaseListBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Chase ID")
	private java.lang.Integer chaseId;
	@org.kie.api.definition.type.Label("CM User")
	private java.lang.String CMUser;
	@org.kie.api.definition.type.Label("Admin User")
	private java.lang.String adminUser;
	@org.kie.api.definition.type.Label("Chaser User")
	private java.lang.String chaserUser;
	@org.kie.api.definition.type.Label("Member Measure")
	private java.lang.String memberMeasure;
	@org.kie.api.definition.type.Label("No Of Providers")
	private int noOfProviders;
	@org.kie.api.definition.type.Label("No Of Overread")
	private int noOfOverread;
	@org.kie.api.definition.type.Label("Abstracter User")
	private java.lang.String abstracterUser;
	@org.kie.api.definition.type.Label("Charts")
	private java.lang.String charts;
	@org.kie.api.definition.type.Label("Counter")
	private int counter;
	@org.kie.api.definition.type.Label("BIC Decision")
	private java.lang.String BICDecision;
	@org.kie.api.definition.type.Label("Final Compliance")
	private java.lang.String finalCompliance;

	@org.kie.api.definition.type.Label("action")
	private java.lang.String action;

	@org.kie.api.definition.type.Label("assignedToUser")
	private java.lang.String assignedToUser;

	@org.kie.api.definition.type.Label("campaign")
	private java.lang.String campaign;

	@org.kie.api.definition.type.Label("campaignId")
	private java.lang.Long campaignId;

	@org.kie.api.definition.type.Label("chaseStatusMstrId")
	private java.lang.Long chaseStatusMstrId;

	@org.kie.api.definition.type.Label("delFlag")
	private java.lang.Boolean delFlag;

	@org.kie.api.definition.type.Label("denomQalifyingEventDate")
	private java.util.Date denomQalifyingEventDate;

	@org.kie.api.definition.type.Label("endDate")
	private java.util.Date endDate;

	@org.kie.api.definition.type.Label("facility")
	private java.lang.Long facility;

	@org.kie.api.definition.type.Label("followpDate")
	private java.util.Date followpDate;

	@org.kie.api.definition.type.Label("healthPlanId")
	private java.lang.Long healthPlanId;

	@org.kie.api.definition.type.Label("id")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("lobId")
	private java.lang.Long lobId;

	@org.kie.api.definition.type.Label("measure")
	private java.lang.Long measure;

	@org.kie.api.definition.type.Label("measureCode")
	private java.lang.String measureCode;

	@org.kie.api.definition.type.Label("measureVersion")
	private java.lang.Long measureVersion;

	@org.kie.api.definition.type.Label("member")
	private java.lang.Long member;

	@org.kie.api.definition.type.Label("mocDetailId")
	private java.lang.Long mocDetailId;

	@org.kie.api.definition.type.Label("overrequired")
	private int overrequired;

	@org.kie.api.definition.type.Label("practitioner")
	private java.lang.Long practitioner;

	@org.kie.api.definition.type.Label("prodId")
	private java.lang.Long prodId;

	@org.kie.api.definition.type.Label("rawChaseId")
	private java.lang.Long rawChaseId;

	@org.kie.api.definition.type.Label("rptFromDate")
	private java.util.Date rptFromDate;

	@org.kie.api.definition.type.Label("rptToDate")
	private java.util.Date rptToDate;

	@org.kie.api.definition.type.Label("spocEmail")
	private java.lang.String spocEmail;

	@org.kie.api.definition.type.Label("spocName")
	private java.lang.String spocName;

	@org.kie.api.definition.type.Label("spocPhoneNumber")
	private java.lang.String spocPhoneNumber;

	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("subMeasureCode")
	private java.lang.String subMeasureCode;

	@org.kie.api.definition.type.Label("user")
	private java.lang.String user;

	@org.kie.api.definition.type.Label("vldFromDate")
	private java.util.Date vldFromDate;

	@org.kie.api.definition.type.Label("vldToDate")
	private java.util.Date vldToDate;

	@org.kie.api.definition.type.Label("workflowInstanceid")
	private java.lang.Long workflowInstanceid;

	public ChaseListBO() {
	}

	public java.lang.Integer getChaseId() {
		return this.chaseId;
	}

	public void setChaseId(java.lang.Integer chaseId) {
		this.chaseId = chaseId;
	}

	public java.lang.String getCMUser() {
		return this.CMUser;
	}

	public void setCMUser(java.lang.String CMUser) {
		this.CMUser = CMUser;
	}

	public java.lang.String getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(java.lang.String adminUser) {
		this.adminUser = adminUser;
	}

	public java.lang.String getChaserUser() {
		return this.chaserUser;
	}

	public void setChaserUser(java.lang.String chaserUser) {
		this.chaserUser = chaserUser;
	}

	public java.lang.String getMemberMeasure() {
		return this.memberMeasure;
	}

	public void setMemberMeasure(java.lang.String memberMeasure) {
		this.memberMeasure = memberMeasure;
	}

	public int getNoOfProviders() {
		return this.noOfProviders;
	}

	public void setNoOfProviders(int noOfProviders) {
		this.noOfProviders = noOfProviders;
	}

	public int getNoOfOverread() {
		return this.noOfOverread;
	}

	public void setNoOfOverread(int noOfOverread) {
		this.noOfOverread = noOfOverread;
	}

	public java.lang.String getAbstracterUser() {
		return this.abstracterUser;
	}

	public void setAbstracterUser(java.lang.String abstracterUser) {
		this.abstracterUser = abstracterUser;
	}

	public java.lang.String getCharts() {
		return this.charts;
	}

	public void setCharts(java.lang.String charts) {
		this.charts = charts;
	}

	public int getCounter() {
		return this.counter;
	}

	public void setCounter(int counter) {
		this.counter = counter;
	}

	public java.lang.String getBICDecision() {
		return this.BICDecision;
	}

	public void setBICDecision(java.lang.String BICDecision) {
		this.BICDecision = BICDecision;
	}

	public java.lang.String getFinalCompliance() {
		return this.finalCompliance;
	}

	public void setFinalCompliance(java.lang.String finalCompliance) {
		this.finalCompliance = finalCompliance;
	}

	public java.lang.String getAction() {
		return this.action;
	}

	public void setAction(java.lang.String action) {
		this.action = action;
	}

	public java.lang.String getAssignedToUser() {
		return this.assignedToUser;
	}

	public void setAssignedToUser(java.lang.String assignedToUser) {
		this.assignedToUser = assignedToUser;
	}

	public java.lang.String getCampaign() {
		return this.campaign;
	}

	public void setCampaign(java.lang.String campaign) {
		this.campaign = campaign;
	}

	public java.lang.Long getCampaignId() {
		return this.campaignId;
	}

	public void setCampaignId(java.lang.Long campaignId) {
		this.campaignId = campaignId;
	}

	public java.lang.Long getChaseStatusMstrId() {
		return this.chaseStatusMstrId;
	}

	public void setChaseStatusMstrId(java.lang.Long chaseStatusMstrId) {
		this.chaseStatusMstrId = chaseStatusMstrId;
	}

	public java.lang.Boolean getDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(java.lang.Boolean delFlag) {
		this.delFlag = delFlag;
	}

	public java.util.Date getDenomQalifyingEventDate() {
		return this.denomQalifyingEventDate;
	}

	public void setDenomQalifyingEventDate(
			java.util.Date denomQalifyingEventDate) {
		this.denomQalifyingEventDate = denomQalifyingEventDate;
	}

	public java.util.Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(java.util.Date endDate) {
		this.endDate = endDate;
	}

	public java.lang.Long getFacility() {
		return this.facility;
	}

	public void setFacility(java.lang.Long facility) {
		this.facility = facility;
	}

	public java.util.Date getFollowpDate() {
		return this.followpDate;
	}

	public void setFollowpDate(java.util.Date followpDate) {
		this.followpDate = followpDate;
	}

	public java.lang.Long getHealthPlanId() {
		return this.healthPlanId;
	}

	public void setHealthPlanId(java.lang.Long healthPlanId) {
		this.healthPlanId = healthPlanId;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.Long getLobId() {
		return this.lobId;
	}

	public void setLobId(java.lang.Long lobId) {
		this.lobId = lobId;
	}

	public java.lang.Long getMeasure() {
		return this.measure;
	}

	public void setMeasure(java.lang.Long measure) {
		this.measure = measure;
	}

	public java.lang.String getMeasureCode() {
		return this.measureCode;
	}

	public void setMeasureCode(java.lang.String measureCode) {
		this.measureCode = measureCode;
	}

	public java.lang.Long getMeasureVersion() {
		return this.measureVersion;
	}

	public void setMeasureVersion(java.lang.Long measureVersion) {
		this.measureVersion = measureVersion;
	}

	public java.lang.Long getMember() {
		return this.member;
	}

	public void setMember(java.lang.Long member) {
		this.member = member;
	}

	public java.lang.Long getMocDetailId() {
		return this.mocDetailId;
	}

	public void setMocDetailId(java.lang.Long mocDetailId) {
		this.mocDetailId = mocDetailId;
	}

	public int getOverrequired() {
		return this.overrequired;
	}

	public void setOverrequired(int overrequired) {
		this.overrequired = overrequired;
	}

	public java.lang.Long getPractitioner() {
		return this.practitioner;
	}

	public void setPractitioner(java.lang.Long practitioner) {
		this.practitioner = practitioner;
	}

	public java.lang.Long getProdId() {
		return this.prodId;
	}

	public void setProdId(java.lang.Long prodId) {
		this.prodId = prodId;
	}

	public java.lang.Long getRawChaseId() {
		return this.rawChaseId;
	}

	public void setRawChaseId(java.lang.Long rawChaseId) {
		this.rawChaseId = rawChaseId;
	}

	public java.util.Date getRptFromDate() {
		return this.rptFromDate;
	}

	public void setRptFromDate(java.util.Date rptFromDate) {
		this.rptFromDate = rptFromDate;
	}

	public java.util.Date getRptToDate() {
		return this.rptToDate;
	}

	public void setRptToDate(java.util.Date rptToDate) {
		this.rptToDate = rptToDate;
	}

	public java.lang.String getSpocEmail() {
		return this.spocEmail;
	}

	public void setSpocEmail(java.lang.String spocEmail) {
		this.spocEmail = spocEmail;
	}

	public java.lang.String getSpocName() {
		return this.spocName;
	}

	public void setSpocName(java.lang.String spocName) {
		this.spocName = spocName;
	}

	public java.lang.String getSpocPhoneNumber() {
		return this.spocPhoneNumber;
	}

	public void setSpocPhoneNumber(java.lang.String spocPhoneNumber) {
		this.spocPhoneNumber = spocPhoneNumber;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getSubMeasureCode() {
		return this.subMeasureCode;
	}

	public void setSubMeasureCode(java.lang.String subMeasureCode) {
		this.subMeasureCode = subMeasureCode;
	}

	public java.lang.String getUser() {
		return this.user;
	}

	public void setUser(java.lang.String user) {
		this.user = user;
	}

	public java.util.Date getVldFromDate() {
		return this.vldFromDate;
	}

	public void setVldFromDate(java.util.Date vldFromDate) {
		this.vldFromDate = vldFromDate;
	}

	public java.util.Date getVldToDate() {
		return this.vldToDate;
	}

	public void setVldToDate(java.util.Date vldToDate) {
		this.vldToDate = vldToDate;
	}

	public java.lang.Long getWorkflowInstanceid() {
		return this.workflowInstanceid;
	}

	public void setWorkflowInstanceid(java.lang.Long workflowInstanceid) {
		this.workflowInstanceid = workflowInstanceid;
	}

	public ChaseListBO(java.lang.Integer chaseId, java.lang.String CMUser,
			java.lang.String adminUser, java.lang.String chaserUser,
			java.lang.String memberMeasure, int noOfProviders,
			int noOfOverread, java.lang.String abstracterUser,
			java.lang.String charts, int counter, java.lang.String BICDecision,
			java.lang.String finalCompliance, java.lang.String action,
			java.lang.String assignedToUser, java.lang.String campaign,
			java.lang.Long campaignId, java.lang.Long chaseStatusMstrId,
			java.lang.Boolean delFlag, java.util.Date denomQalifyingEventDate,
			java.util.Date endDate, java.lang.Long facility,
			java.util.Date followpDate, java.lang.Long healthPlanId,
			java.lang.Long id, java.lang.Long lobId, java.lang.Long measure,
			java.lang.String measureCode, java.lang.Long measureVersion,
			java.lang.Long member, java.lang.Long mocDetailId,
			int overrequired, java.lang.Long practitioner,
			java.lang.Long prodId, java.lang.Long rawChaseId,
			java.util.Date rptFromDate, java.util.Date rptToDate,
			java.lang.String spocEmail, java.lang.String spocName,
			java.lang.String spocPhoneNumber, java.lang.String status,
			java.lang.String subMeasureCode, java.lang.String user,
			java.util.Date vldFromDate, java.util.Date vldToDate,
			java.lang.Long workflowInstanceid) {
		this.chaseId = chaseId;
		this.CMUser = CMUser;
		this.adminUser = adminUser;
		this.chaserUser = chaserUser;
		this.memberMeasure = memberMeasure;
		this.noOfProviders = noOfProviders;
		this.noOfOverread = noOfOverread;
		this.abstracterUser = abstracterUser;
		this.charts = charts;
		this.counter = counter;
		this.BICDecision = BICDecision;
		this.finalCompliance = finalCompliance;
		this.action = action;
		this.assignedToUser = assignedToUser;
		this.campaign = campaign;
		this.campaignId = campaignId;
		this.chaseStatusMstrId = chaseStatusMstrId;
		this.delFlag = delFlag;
		this.denomQalifyingEventDate = denomQalifyingEventDate;
		this.endDate = endDate;
		this.facility = facility;
		this.followpDate = followpDate;
		this.healthPlanId = healthPlanId;
		this.id = id;
		this.lobId = lobId;
		this.measure = measure;
		this.measureCode = measureCode;
		this.measureVersion = measureVersion;
		this.member = member;
		this.mocDetailId = mocDetailId;
		this.overrequired = overrequired;
		this.practitioner = practitioner;
		this.prodId = prodId;
		this.rawChaseId = rawChaseId;
		this.rptFromDate = rptFromDate;
		this.rptToDate = rptToDate;
		this.spocEmail = spocEmail;
		this.spocName = spocName;
		this.spocPhoneNumber = spocPhoneNumber;
		this.status = status;
		this.subMeasureCode = subMeasureCode;
		this.user = user;
		this.vldFromDate = vldFromDate;
		this.vldToDate = vldToDate;
		this.workflowInstanceid = workflowInstanceid;
	}

}