package com.citiustech.mrr.mrrmultiinstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RawChaseBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "RAW_CHSE_ID")
	private int RAW_CHSE_ID;
	@org.kie.api.definition.type.Label(value = "RPT_FRM_DT")
	private java.util.Date RPT_FRM_DT;
	@org.kie.api.definition.type.Label(value = "RPT_TO_DT")
	private java.util.Date RPT_TO_DT;
	@org.kie.api.definition.type.Label(value = "AS_OF_DT")
	private java.util.Date AS_OF_DT;
	@org.kie.api.definition.type.Label(value = "CMPG_CD")
	private java.lang.String CMPG_CD;
	@org.kie.api.definition.type.Label(value = "MSR_VER")
	private int MSR_VER;
	@org.kie.api.definition.type.Label(value = "MSR_CD")
	private java.lang.String MSR_CD;
	@org.kie.api.definition.type.Label(value = "SUBMSR_CD")
	private java.lang.String SUBMSR_CD;
	@org.kie.api.definition.type.Label(value = "MEM_ID")
	private int MEM_ID;
	@org.kie.api.definition.type.Label(value = "PROD_LINE_CD")
	private java.lang.String PROD_LINE_CD;
	@org.kie.api.definition.type.Label(value = "PROD_CD")
	private java.lang.String PROD_CD;
	@org.kie.api.definition.type.Label(value = "HLTHPLN_CD")
	private java.lang.String HLTHPLN_CD;
	@org.kie.api.definition.type.Label(value = "DNRTR_FLG")
	private boolean DNRTR_FLG;
	@org.kie.api.definition.type.Label(value = "NMRTR_FLG")
	private boolean NMRTR_FLG;
	@org.kie.api.definition.type.Label(value = "EXCPTN_FLG")
	private boolean EXCPTN_FLG;
	@org.kie.api.definition.type.Label(value = "GIC_CD")
	private java.lang.String GIC_CD;
	@org.kie.api.definition.type.Label(value = "PCP_ID")
	private int PCP_ID;
	@org.kie.api.definition.type.Label(value = "DNRTR_QLFNG_EVNT_DT")
	private java.util.Date DNRTR_QLFNG_EVNT_DT;
	@org.kie.api.definition.type.Label(value = "DNRTR_QLFNG_EVNT_DT_SRC_SYS")
	private java.lang.String DNRTR_QLFNG_EVNT_DT_SRC_SYS;
	@org.kie.api.definition.type.Label(value = "OVRSMPL_FLG")
	private boolean OVRSMPL_FLG;
	@org.kie.api.definition.type.Label(value = "ORG_ID")
	private int ORG_ID;
	@org.kie.api.definition.type.Label(value = "CNCL_STS_CD")
	private java.lang.String CNCL_STS_CD;
	@org.kie.api.definition.type.Label(value = "MEM_SSUI")
	private java.lang.String MEM_SSUI;
	@org.kie.api.definition.type.Label(value = "PROD_SSUI")
	private java.lang.String PROD_SSUI;
	@org.kie.api.definition.type.Label(value = "PROV_SSUI")
	private java.lang.String PROV_SSUI;
	@org.kie.api.definition.type.Label(value = "DATA_RQST_RESP_FLG")
	private boolean DATA_RQST_RESP_FLG;
	@org.kie.api.definition.type.Label(value = "VLD_FRM_DT")
	private java.util.Date VLD_FRM_DT;
	@org.kie.api.definition.type.Label(value = "VLD_TO_DT")
	private java.util.Date VLD_TO_DT;
	@org.kie.api.definition.type.Label(value = "DEL_FLG")
	private boolean DEL_FLG;

	public RawChaseBO() {
	}

	public int getRAW_CHSE_ID() {
		return this.RAW_CHSE_ID;
	}

	public void setRAW_CHSE_ID(int RAW_CHSE_ID) {
		this.RAW_CHSE_ID = RAW_CHSE_ID;
	}

	public java.util.Date getRPT_FRM_DT() {
		return this.RPT_FRM_DT;
	}

	public void setRPT_FRM_DT(java.util.Date RPT_FRM_DT) {
		this.RPT_FRM_DT = RPT_FRM_DT;
	}

	public java.util.Date getRPT_TO_DT() {
		return this.RPT_TO_DT;
	}

	public void setRPT_TO_DT(java.util.Date RPT_TO_DT) {
		this.RPT_TO_DT = RPT_TO_DT;
	}

	public java.util.Date getAS_OF_DT() {
		return this.AS_OF_DT;
	}

	public void setAS_OF_DT(java.util.Date AS_OF_DT) {
		this.AS_OF_DT = AS_OF_DT;
	}

	public java.lang.String getCMPG_CD() {
		return this.CMPG_CD;
	}

	public void setCMPG_CD(java.lang.String CMPG_CD) {
		this.CMPG_CD = CMPG_CD;
	}

	public int getMSR_VER() {
		return this.MSR_VER;
	}

	public void setMSR_VER(int MSR_VER) {
		this.MSR_VER = MSR_VER;
	}

	public java.lang.String getMSR_CD() {
		return this.MSR_CD;
	}

	public void setMSR_CD(java.lang.String MSR_CD) {
		this.MSR_CD = MSR_CD;
	}

	public java.lang.String getSUBMSR_CD() {
		return this.SUBMSR_CD;
	}

	public void setSUBMSR_CD(java.lang.String SUBMSR_CD) {
		this.SUBMSR_CD = SUBMSR_CD;
	}

	public int getMEM_ID() {
		return this.MEM_ID;
	}

	public void setMEM_ID(int MEM_ID) {
		this.MEM_ID = MEM_ID;
	}

	public java.lang.String getPROD_LINE_CD() {
		return this.PROD_LINE_CD;
	}

	public void setPROD_LINE_CD(java.lang.String PROD_LINE_CD) {
		this.PROD_LINE_CD = PROD_LINE_CD;
	}

	public java.lang.String getPROD_CD() {
		return this.PROD_CD;
	}

	public void setPROD_CD(java.lang.String PROD_CD) {
		this.PROD_CD = PROD_CD;
	}

	public java.lang.String getHLTHPLN_CD() {
		return this.HLTHPLN_CD;
	}

	public void setHLTHPLN_CD(java.lang.String HLTHPLN_CD) {
		this.HLTHPLN_CD = HLTHPLN_CD;
	}

	public boolean isDNRTR_FLG() {
		return this.DNRTR_FLG;
	}

	public void setDNRTR_FLG(boolean DNRTR_FLG) {
		this.DNRTR_FLG = DNRTR_FLG;
	}

	public boolean isNMRTR_FLG() {
		return this.NMRTR_FLG;
	}

	public void setNMRTR_FLG(boolean NMRTR_FLG) {
		this.NMRTR_FLG = NMRTR_FLG;
	}

	public boolean isEXCPTN_FLG() {
		return this.EXCPTN_FLG;
	}

	public void setEXCPTN_FLG(boolean EXCPTN_FLG) {
		this.EXCPTN_FLG = EXCPTN_FLG;
	}

	public java.lang.String getGIC_CD() {
		return this.GIC_CD;
	}

	public void setGIC_CD(java.lang.String GIC_CD) {
		this.GIC_CD = GIC_CD;
	}

	public int getPCP_ID() {
		return this.PCP_ID;
	}

	public void setPCP_ID(int PCP_ID) {
		this.PCP_ID = PCP_ID;
	}

	public java.util.Date getDNRTR_QLFNG_EVNT_DT() {
		return this.DNRTR_QLFNG_EVNT_DT;
	}

	public void setDNRTR_QLFNG_EVNT_DT(java.util.Date DNRTR_QLFNG_EVNT_DT) {
		this.DNRTR_QLFNG_EVNT_DT = DNRTR_QLFNG_EVNT_DT;
	}

	public java.lang.String getDNRTR_QLFNG_EVNT_DT_SRC_SYS() {
		return this.DNRTR_QLFNG_EVNT_DT_SRC_SYS;
	}

	public void setDNRTR_QLFNG_EVNT_DT_SRC_SYS(
			java.lang.String DNRTR_QLFNG_EVNT_DT_SRC_SYS) {
		this.DNRTR_QLFNG_EVNT_DT_SRC_SYS = DNRTR_QLFNG_EVNT_DT_SRC_SYS;
	}

	public boolean isOVRSMPL_FLG() {
		return this.OVRSMPL_FLG;
	}

	public void setOVRSMPL_FLG(boolean OVRSMPL_FLG) {
		this.OVRSMPL_FLG = OVRSMPL_FLG;
	}

	public int getORG_ID() {
		return this.ORG_ID;
	}

	public void setORG_ID(int ORG_ID) {
		this.ORG_ID = ORG_ID;
	}

	public java.lang.String getCNCL_STS_CD() {
		return this.CNCL_STS_CD;
	}

	public void setCNCL_STS_CD(java.lang.String CNCL_STS_CD) {
		this.CNCL_STS_CD = CNCL_STS_CD;
	}

	public java.lang.String getMEM_SSUI() {
		return this.MEM_SSUI;
	}

	public void setMEM_SSUI(java.lang.String MEM_SSUI) {
		this.MEM_SSUI = MEM_SSUI;
	}

	public java.lang.String getPROD_SSUI() {
		return this.PROD_SSUI;
	}

	public void setPROD_SSUI(java.lang.String PROD_SSUI) {
		this.PROD_SSUI = PROD_SSUI;
	}

	public java.lang.String getPROV_SSUI() {
		return this.PROV_SSUI;
	}

	public void setPROV_SSUI(java.lang.String PROV_SSUI) {
		this.PROV_SSUI = PROV_SSUI;
	}

	public boolean isDATA_RQST_RESP_FLG() {
		return this.DATA_RQST_RESP_FLG;
	}

	public void setDATA_RQST_RESP_FLG(boolean DATA_RQST_RESP_FLG) {
		this.DATA_RQST_RESP_FLG = DATA_RQST_RESP_FLG;
	}

	public java.util.Date getVLD_FRM_DT() {
		return this.VLD_FRM_DT;
	}

	public void setVLD_FRM_DT(java.util.Date VLD_FRM_DT) {
		this.VLD_FRM_DT = VLD_FRM_DT;
	}

	public java.util.Date getVLD_TO_DT() {
		return this.VLD_TO_DT;
	}

	public void setVLD_TO_DT(java.util.Date VLD_TO_DT) {
		this.VLD_TO_DT = VLD_TO_DT;
	}

	public boolean isDEL_FLG() {
		return this.DEL_FLG;
	}

	public void setDEL_FLG(boolean DEL_FLG) {
		this.DEL_FLG = DEL_FLG;
	}

	public RawChaseBO(int RAW_CHSE_ID, java.util.Date RPT_FRM_DT,
			java.util.Date RPT_TO_DT, java.util.Date AS_OF_DT,
			java.lang.String CMPG_CD, int MSR_VER, java.lang.String MSR_CD,
			java.lang.String SUBMSR_CD, int MEM_ID,
			java.lang.String PROD_LINE_CD, java.lang.String PROD_CD,
			java.lang.String HLTHPLN_CD, boolean DNRTR_FLG, boolean NMRTR_FLG,
			boolean EXCPTN_FLG, java.lang.String GIC_CD, int PCP_ID,
			java.util.Date DNRTR_QLFNG_EVNT_DT,
			java.lang.String DNRTR_QLFNG_EVNT_DT_SRC_SYS, boolean OVRSMPL_FLG,
			int ORG_ID, java.lang.String CNCL_STS_CD,
			java.lang.String MEM_SSUI, java.lang.String PROD_SSUI,
			java.lang.String PROV_SSUI, boolean DATA_RQST_RESP_FLG,
			java.util.Date VLD_FRM_DT, java.util.Date VLD_TO_DT, boolean DEL_FLG) {
		this.RAW_CHSE_ID = RAW_CHSE_ID;
		this.RPT_FRM_DT = RPT_FRM_DT;
		this.RPT_TO_DT = RPT_TO_DT;
		this.AS_OF_DT = AS_OF_DT;
		this.CMPG_CD = CMPG_CD;
		this.MSR_VER = MSR_VER;
		this.MSR_CD = MSR_CD;
		this.SUBMSR_CD = SUBMSR_CD;
		this.MEM_ID = MEM_ID;
		this.PROD_LINE_CD = PROD_LINE_CD;
		this.PROD_CD = PROD_CD;
		this.HLTHPLN_CD = HLTHPLN_CD;
		this.DNRTR_FLG = DNRTR_FLG;
		this.NMRTR_FLG = NMRTR_FLG;
		this.EXCPTN_FLG = EXCPTN_FLG;
		this.GIC_CD = GIC_CD;
		this.PCP_ID = PCP_ID;
		this.DNRTR_QLFNG_EVNT_DT = DNRTR_QLFNG_EVNT_DT;
		this.DNRTR_QLFNG_EVNT_DT_SRC_SYS = DNRTR_QLFNG_EVNT_DT_SRC_SYS;
		this.OVRSMPL_FLG = OVRSMPL_FLG;
		this.ORG_ID = ORG_ID;
		this.CNCL_STS_CD = CNCL_STS_CD;
		this.MEM_SSUI = MEM_SSUI;
		this.PROD_SSUI = PROD_SSUI;
		this.PROV_SSUI = PROV_SSUI;
		this.DATA_RQST_RESP_FLG = DATA_RQST_RESP_FLG;
		this.VLD_FRM_DT = VLD_FRM_DT;
		this.VLD_TO_DT = VLD_TO_DT;
		this.DEL_FLG = DEL_FLG;
	}

}