package com.citiustech.mrr.mrrmultiinstance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SubProcessBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "chartRejected")
	private java.lang.Boolean chartRejected;
	@org.kie.api.definition.type.Label(value = "adminUser")
	private java.lang.String adminUser;
	@org.kie.api.definition.type.Label(value = "chaserUser")
	private java.lang.String chaserUser;
	@org.kie.api.definition.type.Label(value = "chartUploadedBy")
	private java.lang.String chartUploadedBy;
	@org.kie.api.definition.type.Label(value = "providerFollowup")
	private java.lang.String providerFollowup;

	public SubProcessBO() {
	}

	public java.lang.Boolean getChartRejected() {
		return this.chartRejected;
	}

	public void setChartRejected(java.lang.Boolean chartRejected) {
		this.chartRejected = chartRejected;
	}

	public java.lang.String getAdminUser() {
		return this.adminUser;
	}

	public void setAdminUser(java.lang.String adminUser) {
		this.adminUser = adminUser;
	}

	public java.lang.String getChaserUser() {
		return this.chaserUser;
	}

	public void setChaserUser(java.lang.String chaserUser) {
		this.chaserUser = chaserUser;
	}

	public java.lang.String getChartUploadedBy() {
		return this.chartUploadedBy;
	}

	public void setChartUploadedBy(java.lang.String chartUploadedBy) {
		this.chartUploadedBy = chartUploadedBy;
	}

	public java.lang.String getProviderFollowup() {
		return this.providerFollowup;
	}

	public void setProviderFollowup(java.lang.String providerFollowup) {
		this.providerFollowup = providerFollowup;
	}

	public SubProcessBO(java.lang.Boolean chartRejected,
			java.lang.String adminUser, java.lang.String chaserUser,
			java.lang.String chartUploadedBy, java.lang.String providerFollowup) {
		this.chartRejected = chartRejected;
		this.adminUser = adminUser;
		this.chaserUser = chaserUser;
		this.chartUploadedBy = chartUploadedBy;
		this.providerFollowup = providerFollowup;
	}

}