package com.citiustech.mrr;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ManualChaseBO implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "MANUALCHASEBO_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "MANUALCHASEBO_ID_GENERATOR", sequenceName = "MANUALCHASEBO_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("parentProcessID")
	private java.lang.String parentProcessID;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "cpmm")
	private com.citiustech.mrr.CPMM1 cpmm;

	@javax.persistence.ManyToOne(cascade = {javax.persistence.CascadeType.ALL}, fetch = javax.persistence.FetchType.EAGER)
	@org.kie.api.definition.type.Label(value = "cmm")
	private com.citiustech.mrr.CMM1 cmm;

	public ManualChaseBO() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getParentProcessID() {
		return this.parentProcessID;
	}

	public void setParentProcessID(java.lang.String parentProcessID) {
		this.parentProcessID = parentProcessID;
	}

	public com.citiustech.mrr.CPMM1 getCpmm() {
		return this.cpmm;
	}

	public void setCpmm(com.citiustech.mrr.CPMM1 cpmm) {
		this.cpmm = cpmm;
	}

	public com.citiustech.mrr.CMM1 getCmm() {
		return this.cmm;
	}

	public void setCmm(com.citiustech.mrr.CMM1 cmm) {
		this.cmm = cmm;
	}

	public ManualChaseBO(java.lang.Long id, java.lang.String parentProcessID,
			com.citiustech.mrr.CPMM1 cpmm, com.citiustech.mrr.CMM1 cmm) {
		this.id = id;
		this.parentProcessID = parentProcessID;
		this.cpmm = cpmm;
		this.cmm = cmm;
	}

}